<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypelocation="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>random_pepper_driver</name>
  <version>0.2.0</version>
  <description>Conduce a Pepper con velocidades aleatorias (random_driver.cpp del Tutorial V8, en rclcpp).</description>
  <maintainer email="kevin.inofuente.colque.27@gmail.com">KevinInoCol</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>geometry_msgs</depend>
  <depend>rclcpp</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
