<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypelocation="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>pepper_description</name>
  <version>0.2.0</version>
  <description>Modelo URDF de Pepper 1.0 para ROS 2 Jazzy (Tutorial V9), con la nomenclatura del V8.</description>
  <maintainer email="kevin.inofuente.colque.27@gmail.com">KevinInoCol</maintainer>
  <license>Apache-2.0</license>
  <author>Karsten Knese</author>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>joint_state_publisher</exec_depend>
  <exec_depend>joint_state_publisher_gui</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>xacro</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
